title: Claas Beger
description: A small insight into what I like to develop and what I am interested in.

author:
  name: ClaasBeger
  email: claasbeger@gmail.com
description: > 
  I like to develop useful things and learn about all sorts of fascinating topics in Computer Science, especially relating to Artificial Intelligence.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
minima:
  date_format: "%b %-d, %Y"

# Social links in footer
social_links:
  github: ClaasBeger
  linkedin: claas-beger-272b11187
  youtube_channel: UCXHXUEs0a9DW4FwMTE3qZDw

# Navigation Menu
menu:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Education"
    url: "/education"
  - title: "Professional"
    url: "/professional"
  - title: "Certificates"
    url: "/certificates"

# Build settings
theme: jekyll-theme-slate

# - about.md

# Build settings
theme: jekyll-theme-slate
