title: Claas Beger -- Open Repositories
description: A short overview of my theoretical areas of interest and their practical implementation approaches.


title: Claas Beger -- Open Repositories
author:
  name: ClaasBeger
  email: claasbeger@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  A short overview of my theoretical areas of interest and their practical implementation approaches.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  ClaasBeger
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: Claas Beger
    # pinterest: jekyll
    # youtube: jekyll
    youtube_channel: UCXHXUEs0a9DW4FwMTE3qZDw
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-slate

plugins:
 - jekyll-feed
 - jekyll-seo-tag
